# Generated by Django 5.1.15 on 2025-12-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamenApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensayoclinico',
            name='investigadores',
            field=models.ManyToManyField(null=True, related_name='ensayos_investigador', to='ExamenApp.investigador'),
        ),
    ]
