# Generated by Django 5.1.15 on 2025-12-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamenApp', '0002_ensayoclinico_investigadores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ensayoclinico',
            name='investigadores',
        ),
    ]
